namespace: loki

grafana:
  namespace: ""

store: filesystem  # filesystem | s3
s3:
  region: ""
  bucket: ""
  endpoint: ""
  encrypted: true
  insecure: false
  pathStyle: false

prometheus:
  enable: true

tracing:
  enable: false
  dsUid: tempo
  host: tempo
  endpoint: http://tempo:14268/api/traces
  samplerType: ratelimiting
  samplerParam: 0.2
